// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 994225293;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_lamina_dart',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleInitApp();

  Future<Float64List> crateApiSimpleProcessEcgClean({
    required List<double> signal,
    required double samplingRate,
    required String method,
  });

  Future<List<bool>> crateApiSimpleProcessEcgFindpeaks({
    required List<double> signal,
    required double samplingRate,
  });

  Future<Float64List> crateApiSimpleProcessEdaClean({
    required List<double> signal,
    required double samplingRate,
  });

  Future<List<bool>> crateApiSimpleProcessEdaFindpeaks({
    required List<double> phasicSignal,
  });

  Future<Float64List> crateApiSimpleProcessEdaPhasic({
    required List<double> signal,
    required double samplingRate,
  });

  Future<double?> crateApiSimpleProcessHrvMeanNn({
    required List<double> intervals,
  });

  Future<double?> crateApiSimpleProcessHrvRmssd({
    required List<double> intervals,
  });

  Future<Float64List> crateApiSimpleProcessPeaksToIntervals({
    required List<bool> peaks,
    required double samplingRate,
  });

  Future<Float64List> crateApiSimpleProcessPpgClean({
    required List<double> signal,
    required double samplingRate,
  });

  Future<List<bool>> crateApiSimpleProcessPpgFindpeaks({
    required List<double> signal,
    required double samplingRate,
  });

  Future<Float64List> crateApiSimpleProcessRspClean({
    required List<double> signal,
    required double samplingRate,
  });

  Future<List<bool>> crateApiSimpleProcessRspFindpeaks({
    required List<double> cleanedSignal,
  });

  Future<double> crateApiSimpleProcessSampleEntropy({
    required List<double> signal,
    required BigInt m,
    required double r,
  });

  Future<Float64List> crateApiSimpleProcessSignalFilter({
    required List<double> signal,
    required double samplingRate,
    double? lowcut,
    double? highcut,
    required BigInt order,
  });

  Future<List<bool>> crateApiSimpleProcessSignalFindpeaks({
    required List<double> signal,
  });

  Future<Float64List> crateApiSimpleProcessSignalSmoothMovingAverage({
    required List<double> signal,
    required BigInt windowSize,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<Float64List> crateApiSimpleProcessEcgClean({
    required List<double> signal,
    required double samplingRate,
    required String method,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(signal, serializer);
          sse_encode_f_64(samplingRate, serializer);
          sse_encode_String(method, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessEcgCleanConstMeta,
        argValues: [signal, samplingRate, method],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessEcgCleanConstMeta =>
      const TaskConstMeta(
        debugName: "process_ecg_clean",
        argNames: ["signal", "samplingRate", "method"],
      );

  @override
  Future<List<bool>> crateApiSimpleProcessEcgFindpeaks({
    required List<double> signal,
    required double samplingRate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(signal, serializer);
          sse_encode_f_64(samplingRate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessEcgFindpeaksConstMeta,
        argValues: [signal, samplingRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessEcgFindpeaksConstMeta =>
      const TaskConstMeta(
        debugName: "process_ecg_findpeaks",
        argNames: ["signal", "samplingRate"],
      );

  @override
  Future<Float64List> crateApiSimpleProcessEdaClean({
    required List<double> signal,
    required double samplingRate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(signal, serializer);
          sse_encode_f_64(samplingRate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessEdaCleanConstMeta,
        argValues: [signal, samplingRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessEdaCleanConstMeta =>
      const TaskConstMeta(
        debugName: "process_eda_clean",
        argNames: ["signal", "samplingRate"],
      );

  @override
  Future<List<bool>> crateApiSimpleProcessEdaFindpeaks({
    required List<double> phasicSignal,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(phasicSignal, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessEdaFindpeaksConstMeta,
        argValues: [phasicSignal],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessEdaFindpeaksConstMeta =>
      const TaskConstMeta(
        debugName: "process_eda_findpeaks",
        argNames: ["phasicSignal"],
      );

  @override
  Future<Float64List> crateApiSimpleProcessEdaPhasic({
    required List<double> signal,
    required double samplingRate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(signal, serializer);
          sse_encode_f_64(samplingRate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessEdaPhasicConstMeta,
        argValues: [signal, samplingRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessEdaPhasicConstMeta =>
      const TaskConstMeta(
        debugName: "process_eda_phasic",
        argNames: ["signal", "samplingRate"],
      );

  @override
  Future<double?> crateApiSimpleProcessHrvMeanNn({
    required List<double> intervals,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(intervals, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessHrvMeanNnConstMeta,
        argValues: [intervals],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessHrvMeanNnConstMeta =>
      const TaskConstMeta(
        debugName: "process_hrv_mean_nn",
        argNames: ["intervals"],
      );

  @override
  Future<double?> crateApiSimpleProcessHrvRmssd({
    required List<double> intervals,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(intervals, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessHrvRmssdConstMeta,
        argValues: [intervals],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessHrvRmssdConstMeta =>
      const TaskConstMeta(
        debugName: "process_hrv_rmssd",
        argNames: ["intervals"],
      );

  @override
  Future<Float64List> crateApiSimpleProcessPeaksToIntervals({
    required List<bool> peaks,
    required double samplingRate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_bool(peaks, serializer);
          sse_encode_f_64(samplingRate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessPeaksToIntervalsConstMeta,
        argValues: [peaks, samplingRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessPeaksToIntervalsConstMeta =>
      const TaskConstMeta(
        debugName: "process_peaks_to_intervals",
        argNames: ["peaks", "samplingRate"],
      );

  @override
  Future<Float64List> crateApiSimpleProcessPpgClean({
    required List<double> signal,
    required double samplingRate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(signal, serializer);
          sse_encode_f_64(samplingRate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessPpgCleanConstMeta,
        argValues: [signal, samplingRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessPpgCleanConstMeta =>
      const TaskConstMeta(
        debugName: "process_ppg_clean",
        argNames: ["signal", "samplingRate"],
      );

  @override
  Future<List<bool>> crateApiSimpleProcessPpgFindpeaks({
    required List<double> signal,
    required double samplingRate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(signal, serializer);
          sse_encode_f_64(samplingRate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessPpgFindpeaksConstMeta,
        argValues: [signal, samplingRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessPpgFindpeaksConstMeta =>
      const TaskConstMeta(
        debugName: "process_ppg_findpeaks",
        argNames: ["signal", "samplingRate"],
      );

  @override
  Future<Float64List> crateApiSimpleProcessRspClean({
    required List<double> signal,
    required double samplingRate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(signal, serializer);
          sse_encode_f_64(samplingRate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessRspCleanConstMeta,
        argValues: [signal, samplingRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessRspCleanConstMeta =>
      const TaskConstMeta(
        debugName: "process_rsp_clean",
        argNames: ["signal", "samplingRate"],
      );

  @override
  Future<List<bool>> crateApiSimpleProcessRspFindpeaks({
    required List<double> cleanedSignal,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(cleanedSignal, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessRspFindpeaksConstMeta,
        argValues: [cleanedSignal],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessRspFindpeaksConstMeta =>
      const TaskConstMeta(
        debugName: "process_rsp_findpeaks",
        argNames: ["cleanedSignal"],
      );

  @override
  Future<double> crateApiSimpleProcessSampleEntropy({
    required List<double> signal,
    required BigInt m,
    required double r,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(signal, serializer);
          sse_encode_usize(m, serializer);
          sse_encode_f_64(r, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessSampleEntropyConstMeta,
        argValues: [signal, m, r],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessSampleEntropyConstMeta =>
      const TaskConstMeta(
        debugName: "process_sample_entropy",
        argNames: ["signal", "m", "r"],
      );

  @override
  Future<Float64List> crateApiSimpleProcessSignalFilter({
    required List<double> signal,
    required double samplingRate,
    double? lowcut,
    double? highcut,
    required BigInt order,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(signal, serializer);
          sse_encode_f_64(samplingRate, serializer);
          sse_encode_opt_box_autoadd_f_64(lowcut, serializer);
          sse_encode_opt_box_autoadd_f_64(highcut, serializer);
          sse_encode_usize(order, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessSignalFilterConstMeta,
        argValues: [signal, samplingRate, lowcut, highcut, order],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessSignalFilterConstMeta =>
      const TaskConstMeta(
        debugName: "process_signal_filter",
        argNames: ["signal", "samplingRate", "lowcut", "highcut", "order"],
      );

  @override
  Future<List<bool>> crateApiSimpleProcessSignalFindpeaks({
    required List<double> signal,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(signal, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessSignalFindpeaksConstMeta,
        argValues: [signal],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessSignalFindpeaksConstMeta =>
      const TaskConstMeta(
        debugName: "process_signal_findpeaks",
        argNames: ["signal"],
      );

  @override
  Future<Float64List> crateApiSimpleProcessSignalSmoothMovingAverage({
    required List<double> signal,
    required BigInt windowSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(signal, serializer);
          sse_encode_usize(windowSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessSignalSmoothMovingAverageConstMeta,
        argValues: [signal, windowSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessSignalSmoothMovingAverageConstMeta =>
      const TaskConstMeta(
        debugName: "process_signal_smooth_moving_average",
        argNames: ["signal", "windowSize"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<bool> dco_decode_list_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bool).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <bool>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bool(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bool(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_64_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(
      self is Float64List ? self : Float64List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
