// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AutonomicEstimator>>
abstract class AutonomicEstimator implements RustOpaqueInterface {
  static Future<AutonomicEstimator> default_() =>
      RustLib.instance.api.crateApiAutonomicAutonomicEstimatorDefault();

  Future<AutonomicState> estimateFromVector();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AutonomicEstimator> newInstance() =>
      RustLib.instance.api.crateApiAutonomicAutonomicEstimatorNew();
}

class AutonomicState {
  final double timestamp;
  final double durationSec;
  final CardiacState cardiac;
  final ElectrodermalState electrodermal;
  final RespiratoryState respiratory;
  final CouplingState coupling;
  final double? activationScore;
  final double? regulationScore;

  const AutonomicState({
    required this.timestamp,
    required this.durationSec,
    required this.cardiac,
    required this.electrodermal,
    required this.respiratory,
    required this.coupling,
    this.activationScore,
    this.regulationScore,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^
      durationSec.hashCode ^
      cardiac.hashCode ^
      electrodermal.hashCode ^
      respiratory.hashCode ^
      coupling.hashCode ^
      activationScore.hashCode ^
      regulationScore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AutonomicState &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          durationSec == other.durationSec &&
          cardiac == other.cardiac &&
          electrodermal == other.electrodermal &&
          respiratory == other.respiratory &&
          coupling == other.coupling &&
          activationScore == other.activationScore &&
          regulationScore == other.regulationScore;
}

class CardiacState {
  final double? variabilityIndex;
  final double? heartRateIndex;
  final double? recoveryEvidence;
  final int beatCount;

  const CardiacState({
    this.variabilityIndex,
    this.heartRateIndex,
    this.recoveryEvidence,
    required this.beatCount,
  });

  @override
  int get hashCode =>
      variabilityIndex.hashCode ^
      heartRateIndex.hashCode ^
      recoveryEvidence.hashCode ^
      beatCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CardiacState &&
          runtimeType == other.runtimeType &&
          variabilityIndex == other.variabilityIndex &&
          heartRateIndex == other.heartRateIndex &&
          recoveryEvidence == other.recoveryEvidence &&
          beatCount == other.beatCount;
}

class CouplingState {
  final double? resphrCouplingIndex;
  final double? phaseCouplingIndex;
  final double? pulseDelayIndex;
  final int associationCount;

  const CouplingState({
    this.resphrCouplingIndex,
    this.phaseCouplingIndex,
    this.pulseDelayIndex,
    required this.associationCount,
  });

  @override
  int get hashCode =>
      resphrCouplingIndex.hashCode ^
      phaseCouplingIndex.hashCode ^
      pulseDelayIndex.hashCode ^
      associationCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CouplingState &&
          runtimeType == other.runtimeType &&
          resphrCouplingIndex == other.resphrCouplingIndex &&
          phaseCouplingIndex == other.phaseCouplingIndex &&
          pulseDelayIndex == other.pulseDelayIndex &&
          associationCount == other.associationCount;
}

class ElectrodermalState {
  final double? tonicLevelIndex;
  final double? phasicActivationIndex;
  final double? scrRateIndex;
  final int scrCount;

  const ElectrodermalState({
    this.tonicLevelIndex,
    this.phasicActivationIndex,
    this.scrRateIndex,
    required this.scrCount,
  });

  @override
  int get hashCode =>
      tonicLevelIndex.hashCode ^
      phasicActivationIndex.hashCode ^
      scrRateIndex.hashCode ^
      scrCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ElectrodermalState &&
          runtimeType == other.runtimeType &&
          tonicLevelIndex == other.tonicLevelIndex &&
          phasicActivationIndex == other.phasicActivationIndex &&
          scrRateIndex == other.scrRateIndex &&
          scrCount == other.scrCount;
}

class RespiratoryState {
  final double? rateIndex;
  final double? amplitudeIndex;
  final double? regularityIndex;
  final int cycleCount;

  const RespiratoryState({
    this.rateIndex,
    this.amplitudeIndex,
    this.regularityIndex,
    required this.cycleCount,
  });

  @override
  int get hashCode =>
      rateIndex.hashCode ^
      amplitudeIndex.hashCode ^
      regularityIndex.hashCode ^
      cycleCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RespiratoryState &&
          runtimeType == other.runtimeType &&
          rateIndex == other.rateIndex &&
          amplitudeIndex == other.amplitudeIndex &&
          regularityIndex == other.regularityIndex &&
          cycleCount == other.cycleCount;
}
