// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`, `from`

Future<Float64List> processEcgClean({
  required List<double> signal,
  required double samplingRate,
  required String method,
}) => RustLib.instance.api.crateApiEcgProcessEcgClean(
  signal: signal,
  samplingRate: samplingRate,
  method: method,
);

Future<List<int>> processEcgFindpeaks({
  required List<double> signal,
  required double samplingRate,
  EcgPeakDetectionConfig? config,
}) => RustLib.instance.api.crateApiEcgProcessEcgFindpeaks(
  signal: signal,
  samplingRate: samplingRate,
  config: config,
);

Future<Uint8List> processEcgFindpeaksMask({
  required List<double> signal,
  required double samplingRate,
}) => RustLib.instance.api.crateApiEcgProcessEcgFindpeaksMask(
  signal: signal,
  samplingRate: samplingRate,
);

class EcgPeakDetectionConfig {
  final double? lowcut;
  final double? highcut;
  final int? filterOrder;
  final double? integrationWindowSec;
  final double? refractoryPeriodSec;
  final bool? searchback;
  final double? thresholdMultiplier;

  const EcgPeakDetectionConfig({
    this.lowcut,
    this.highcut,
    this.filterOrder,
    this.integrationWindowSec,
    this.refractoryPeriodSec,
    this.searchback,
    this.thresholdMultiplier,
  });

  static Future<EcgPeakDetectionConfig> default_() =>
      RustLib.instance.api.crateApiEcgEcgPeakDetectionConfigDefault();

  @override
  int get hashCode =>
      lowcut.hashCode ^
      highcut.hashCode ^
      filterOrder.hashCode ^
      integrationWindowSec.hashCode ^
      refractoryPeriodSec.hashCode ^
      searchback.hashCode ^
      thresholdMultiplier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EcgPeakDetectionConfig &&
          runtimeType == other.runtimeType &&
          lowcut == other.lowcut &&
          highcut == other.highcut &&
          filterOrder == other.filterOrder &&
          integrationWindowSec == other.integrationWindowSec &&
          refractoryPeriodSec == other.refractoryPeriodSec &&
          searchback == other.searchback &&
          thresholdMultiplier == other.thresholdMultiplier;
}
