// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

Future<Float64List> processEdaClean({
  required List<double> signal,
  required double samplingRate,
}) => RustLib.instance.api.crateApiEdaProcessEdaClean(
  signal: signal,
  samplingRate: samplingRate,
);

Future<Float64List> processEdaPhasic({
  required List<double> signal,
  required double samplingRate,
}) => RustLib.instance.api.crateApiEdaProcessEdaPhasic(
  signal: signal,
  samplingRate: samplingRate,
);

Future<EdaComponentSignals> processEdaDecompose({
  required List<double> signal,
  required double samplingRate,
  EdaDecompositionConfig? config,
}) => RustLib.instance.api.crateApiEdaProcessEdaDecompose(
  signal: signal,
  samplingRate: samplingRate,
  config: config,
);

Future<List<int>> processEdaFindpeaks({
  required List<double> phasicSignal,
  required double samplingRate,
  EdaPeakDetectionConfig? config,
}) => RustLib.instance.api.crateApiEdaProcessEdaFindpeaks(
  phasicSignal: phasicSignal,
  samplingRate: samplingRate,
  config: config,
);

Future<List<EdaPeakEvent>> processEdaFindpeaksEvents({
  required List<double> phasicSignal,
  required double samplingRate,
  EdaPeakDetectionConfig? config,
}) => RustLib.instance.api.crateApiEdaProcessEdaFindpeaksEvents(
  phasicSignal: phasicSignal,
  samplingRate: samplingRate,
  config: config,
);

Future<Uint8List> processEdaFindpeaksMask({
  required List<double> phasicSignal,
  required double samplingRate,
}) => RustLib.instance.api.crateApiEdaProcessEdaFindpeaksMask(
  phasicSignal: phasicSignal,
  samplingRate: samplingRate,
);

class EdaComponentSignals {
  final Float64List tonic;
  final Float64List phasic;

  const EdaComponentSignals({required this.tonic, required this.phasic});

  @override
  int get hashCode => tonic.hashCode ^ phasic.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EdaComponentSignals &&
          runtimeType == other.runtimeType &&
          tonic == other.tonic &&
          phasic == other.phasic;
}

class EdaDecompositionConfig {
  final double? tonicCutoffHz;
  final int? filterOrder;

  const EdaDecompositionConfig({this.tonicCutoffHz, this.filterOrder});

  static Future<EdaDecompositionConfig> default_() =>
      RustLib.instance.api.crateApiEdaEdaDecompositionConfigDefault();

  @override
  int get hashCode => tonicCutoffHz.hashCode ^ filterOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EdaDecompositionConfig &&
          runtimeType == other.runtimeType &&
          tonicCutoffHz == other.tonicCutoffHz &&
          filterOrder == other.filterOrder;
}

class EdaPeakDetectionConfig {
  final double? minAmplitude;
  final double? minProminence;
  final double? minDistanceSec;
  final double? minRiseTimeSec;
  final double? maxRiseTimeSec;

  const EdaPeakDetectionConfig({
    this.minAmplitude,
    this.minProminence,
    this.minDistanceSec,
    this.minRiseTimeSec,
    this.maxRiseTimeSec,
  });

  static Future<EdaPeakDetectionConfig> default_() =>
      RustLib.instance.api.crateApiEdaEdaPeakDetectionConfigDefault();

  @override
  int get hashCode =>
      minAmplitude.hashCode ^
      minProminence.hashCode ^
      minDistanceSec.hashCode ^
      minRiseTimeSec.hashCode ^
      maxRiseTimeSec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EdaPeakDetectionConfig &&
          runtimeType == other.runtimeType &&
          minAmplitude == other.minAmplitude &&
          minProminence == other.minProminence &&
          minDistanceSec == other.minDistanceSec &&
          minRiseTimeSec == other.minRiseTimeSec &&
          maxRiseTimeSec == other.maxRiseTimeSec;
}

class EdaPeakEvent {
  final int onsetIndex;
  final int peakIndex;
  final double amplitude;
  final double riseTimeSec;

  const EdaPeakEvent({
    required this.onsetIndex,
    required this.peakIndex,
    required this.amplitude,
    required this.riseTimeSec,
  });

  @override
  int get hashCode =>
      onsetIndex.hashCode ^
      peakIndex.hashCode ^
      amplitude.hashCode ^
      riseTimeSec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EdaPeakEvent &&
          runtimeType == other.runtimeType &&
          onsetIndex == other.onsetIndex &&
          peakIndex == other.peakIndex &&
          amplitude == other.amplitude &&
          riseTimeSec == other.riseTimeSec;
}
