// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`, `fmt`, `from`

/// Primary error type for Lamina physiological signal processing operations.
class SignalError implements FrbException {
  final String message;

  const SignalError({required this.message});

  static Future<SignalError> dimensionMismatch() =>
      RustLib.instance.api.crateApiErrorSignalErrorDimensionMismatch();

  static Future<SignalError> emptySignal() =>
      RustLib.instance.api.crateApiErrorSignalErrorEmptySignal();

  static Future<SignalError> insufficientPeaks({
    required int required_,
    required int provided,
  }) => RustLib.instance.api.crateApiErrorSignalErrorInsufficientPeaks(
    required_: required_,
    provided: provided,
  );

  static Future<SignalError> invalidSamplingRate({required double rate}) =>
      RustLib.instance.api.crateApiErrorSignalErrorInvalidSamplingRate(
        rate: rate,
      );

  static Future<SignalError> nonFiniteInput() =>
      RustLib.instance.api.crateApiErrorSignalErrorNonFiniteInput();

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignalError &&
          runtimeType == other.runtimeType &&
          message == other.message;
}
