// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'eda.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rsp.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

Future<CardiacFeatures> extractCardiacFeatures({
  required List<int> rPeaks,
  required double samplingRate,
  required double offsetSec,
  required FeatureWindow window,
}) => RustLib.instance.api.crateApiFeaturesExtractCardiacFeatures(
  rPeaks: rPeaks,
  samplingRate: samplingRate,
  offsetSec: offsetSec,
  window: window,
);

Future<EdaFeatures> extractEdaFeatures({
  required List<double> tonic,
  required List<double> phasic,
  required List<EdaPeakEvent> events,
  required double samplingRate,
  required double offsetSec,
  required FeatureWindow window,
}) => RustLib.instance.api.crateApiFeaturesExtractEdaFeatures(
  tonic: tonic,
  phasic: phasic,
  events: events,
  samplingRate: samplingRate,
  offsetSec: offsetSec,
  window: window,
);

Future<RespirationFeatures> extractRespirationFeatures({
  required List<RespirationCycle> cycles,
  required double samplingRate,
  required double offsetSec,
  required FeatureWindow window,
}) => RustLib.instance.api.crateApiFeaturesExtractRespirationFeatures(
  cycles: cycles,
  samplingRate: samplingRate,
  offsetSec: offsetSec,
  window: window,
);

class CardiacFeatures {
  final double? meanHrBpm;
  final double? medianHrBpm;
  final double? sdnnMs;
  final double? rmssdMs;
  final double? pnn50;
  final double? rrMeanMs;
  final double? rrStdMs;
  final int beatCount;

  const CardiacFeatures({
    this.meanHrBpm,
    this.medianHrBpm,
    this.sdnnMs,
    this.rmssdMs,
    this.pnn50,
    this.rrMeanMs,
    this.rrStdMs,
    required this.beatCount,
  });

  @override
  int get hashCode =>
      meanHrBpm.hashCode ^
      medianHrBpm.hashCode ^
      sdnnMs.hashCode ^
      rmssdMs.hashCode ^
      pnn50.hashCode ^
      rrMeanMs.hashCode ^
      rrStdMs.hashCode ^
      beatCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CardiacFeatures &&
          runtimeType == other.runtimeType &&
          meanHrBpm == other.meanHrBpm &&
          medianHrBpm == other.medianHrBpm &&
          sdnnMs == other.sdnnMs &&
          rmssdMs == other.rmssdMs &&
          pnn50 == other.pnn50 &&
          rrMeanMs == other.rrMeanMs &&
          rrStdMs == other.rrStdMs &&
          beatCount == other.beatCount;
}

class EdaFeatures {
  final double? meanTonicUs;
  final double? medianTonicUs;
  final double? tonicStdUs;
  final double? meanPhasicUs;
  final double? phasicStdUs;
  final int scrCount;
  final double? scrRatePerMin;
  final double? meanScrAmplitudeUs;
  final double? medianScrAmplitudeUs;
  final double? meanScrRiseTimeSec;

  const EdaFeatures({
    this.meanTonicUs,
    this.medianTonicUs,
    this.tonicStdUs,
    this.meanPhasicUs,
    this.phasicStdUs,
    required this.scrCount,
    this.scrRatePerMin,
    this.meanScrAmplitudeUs,
    this.medianScrAmplitudeUs,
    this.meanScrRiseTimeSec,
  });

  @override
  int get hashCode =>
      meanTonicUs.hashCode ^
      medianTonicUs.hashCode ^
      tonicStdUs.hashCode ^
      meanPhasicUs.hashCode ^
      phasicStdUs.hashCode ^
      scrCount.hashCode ^
      scrRatePerMin.hashCode ^
      meanScrAmplitudeUs.hashCode ^
      medianScrAmplitudeUs.hashCode ^
      meanScrRiseTimeSec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EdaFeatures &&
          runtimeType == other.runtimeType &&
          meanTonicUs == other.meanTonicUs &&
          medianTonicUs == other.medianTonicUs &&
          tonicStdUs == other.tonicStdUs &&
          meanPhasicUs == other.meanPhasicUs &&
          phasicStdUs == other.phasicStdUs &&
          scrCount == other.scrCount &&
          scrRatePerMin == other.scrRatePerMin &&
          meanScrAmplitudeUs == other.meanScrAmplitudeUs &&
          medianScrAmplitudeUs == other.medianScrAmplitudeUs &&
          meanScrRiseTimeSec == other.meanScrRiseTimeSec;
}

class FeatureWindow {
  final double startTimeSec;
  final double endTimeSec;

  const FeatureWindow({required this.startTimeSec, required this.endTimeSec});

  @override
  int get hashCode => startTimeSec.hashCode ^ endTimeSec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeatureWindow &&
          runtimeType == other.runtimeType &&
          startTimeSec == other.startTimeSec &&
          endTimeSec == other.endTimeSec;
}

class RespirationFeatures {
  final double? meanRateBpm;
  final double? medianRateBpm;
  final double? rateStdBpm;
  final double? meanCycleDurationSec;
  final int cycleCount;
  final double? meanAmplitude;
  final double? amplitudeStd;

  const RespirationFeatures({
    this.meanRateBpm,
    this.medianRateBpm,
    this.rateStdBpm,
    this.meanCycleDurationSec,
    required this.cycleCount,
    this.meanAmplitude,
    this.amplitudeStd,
  });

  @override
  int get hashCode =>
      meanRateBpm.hashCode ^
      medianRateBpm.hashCode ^
      rateStdBpm.hashCode ^
      meanCycleDurationSec.hashCode ^
      cycleCount.hashCode ^
      meanAmplitude.hashCode ^
      amplitudeStd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RespirationFeatures &&
          runtimeType == other.runtimeType &&
          meanRateBpm == other.meanRateBpm &&
          medianRateBpm == other.medianRateBpm &&
          rateStdBpm == other.rateStdBpm &&
          meanCycleDurationSec == other.meanCycleDurationSec &&
          cycleCount == other.cycleCount &&
          meanAmplitude == other.meanAmplitude &&
          amplitudeStd == other.amplitudeStd;
}
