// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Float64List> processPeaksToIntervals({
  required List<int> peaks,
  required double samplingRate,
  required int totalSamples,
}) => RustLib.instance.api.crateApiHrvProcessPeaksToIntervals(
  peaks: peaks,
  samplingRate: samplingRate,
  totalSamples: totalSamples,
);

Future<double> processHrvRmssd({required List<double> intervals}) =>
    RustLib.instance.api.crateApiHrvProcessHrvRmssd(intervals: intervals);

Future<double> processHrvMeanNn({required List<double> intervals}) =>
    RustLib.instance.api.crateApiHrvProcessHrvMeanNn(intervals: intervals);

Future<double> processHrvSdnn({required List<double> intervals}) =>
    RustLib.instance.api.crateApiHrvProcessHrvSdnn(intervals: intervals);

Future<double> processHrvPnn50({required List<double> intervals}) =>
    RustLib.instance.api.crateApiHrvProcessHrvPnn50(intervals: intervals);
