// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'rsp.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CardiacRespiratoryEvent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`

Future<List<PulseTimingResult>> computeEcgPpgTiming({
  required List<int> ecgPeaks,
  required double ecgSamplingRate,
  required double ecgOffsetSec,
  required List<int> ppgPeaks,
  required double ppgSamplingRate,
  required double ppgOffsetSec,
  PulseTimingConfig? config,
}) => RustLib.instance.api.crateApiMultimodalComputeEcgPpgTiming(
  ecgPeaks: ecgPeaks,
  ecgSamplingRate: ecgSamplingRate,
  ecgOffsetSec: ecgOffsetSec,
  ppgPeaks: ppgPeaks,
  ppgSamplingRate: ppgSamplingRate,
  ppgOffsetSec: ppgOffsetSec,
  config: config,
);

Future<PhaseCouplingResult> computeCardiorespiratoryPhaseCoupling({
  required List<double> phases,
}) => RustLib.instance.api
    .crateApiMultimodalComputeCardiorespiratoryPhaseCoupling(phases: phases);

Future<RsaResult> computeRsa({
  required List<int> rPeaks,
  required double ecgSamplingRate,
  required double ecgOffsetSec,
  required List<RespirationCycle> rspCycles,
  required double rspSamplingRate,
  required double rspOffsetSec,
}) => RustLib.instance.api.crateApiMultimodalComputeRsa(
  rPeaks: rPeaks,
  ecgSamplingRate: ecgSamplingRate,
  ecgOffsetSec: ecgOffsetSec,
  rspCycles: rspCycles,
  rspSamplingRate: rspSamplingRate,
  rspOffsetSec: rspOffsetSec,
);

class PhaseCouplingResult {
  final double meanPhaseRad;
  final double vectorLength;
  final int sampleCount;

  const PhaseCouplingResult({
    required this.meanPhaseRad,
    required this.vectorLength,
    required this.sampleCount,
  });

  @override
  int get hashCode =>
      meanPhaseRad.hashCode ^ vectorLength.hashCode ^ sampleCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PhaseCouplingResult &&
          runtimeType == other.runtimeType &&
          meanPhaseRad == other.meanPhaseRad &&
          vectorLength == other.vectorLength &&
          sampleCount == other.sampleCount;
}

class PulseTimingConfig {
  final double? minDelaySec;
  final double? maxDelaySec;

  const PulseTimingConfig({this.minDelaySec, this.maxDelaySec});

  static Future<PulseTimingConfig> default_() =>
      RustLib.instance.api.crateApiMultimodalPulseTimingConfigDefault();

  @override
  int get hashCode => minDelaySec.hashCode ^ maxDelaySec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PulseTimingConfig &&
          runtimeType == other.runtimeType &&
          minDelaySec == other.minDelaySec &&
          maxDelaySec == other.maxDelaySec;
}

class PulseTimingResult {
  final int ecgPeakIndex;
  final int ppgPeakIndex;
  final double ecgTimestampSec;
  final double ppgTimestampSec;
  final double pulseDelaySec;

  const PulseTimingResult({
    required this.ecgPeakIndex,
    required this.ppgPeakIndex,
    required this.ecgTimestampSec,
    required this.ppgTimestampSec,
    required this.pulseDelaySec,
  });

  @override
  int get hashCode =>
      ecgPeakIndex.hashCode ^
      ppgPeakIndex.hashCode ^
      ecgTimestampSec.hashCode ^
      ppgTimestampSec.hashCode ^
      pulseDelaySec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PulseTimingResult &&
          runtimeType == other.runtimeType &&
          ecgPeakIndex == other.ecgPeakIndex &&
          ppgPeakIndex == other.ppgPeakIndex &&
          ecgTimestampSec == other.ecgTimestampSec &&
          ppgTimestampSec == other.ppgTimestampSec &&
          pulseDelaySec == other.pulseDelaySec;
}

class RsaResult {
  final double amplitudeBpm;
  final double amplitudeRrSec;
  final int validBeats;
  final int validCycles;

  const RsaResult({
    required this.amplitudeBpm,
    required this.amplitudeRrSec,
    required this.validBeats,
    required this.validCycles,
  });

  @override
  int get hashCode =>
      amplitudeBpm.hashCode ^
      amplitudeRrSec.hashCode ^
      validBeats.hashCode ^
      validCycles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RsaResult &&
          runtimeType == other.runtimeType &&
          amplitudeBpm == other.amplitudeBpm &&
          amplitudeRrSec == other.amplitudeRrSec &&
          validBeats == other.validBeats &&
          validCycles == other.validCycles;
}
