// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`, `from`

Future<Float64List> processPpgClean({
  required List<double> signal,
  required double samplingRate,
}) => RustLib.instance.api.crateApiPpgProcessPpgClean(
  signal: signal,
  samplingRate: samplingRate,
);

Future<List<int>> processPpgFindpeaks({
  required List<double> signal,
  required double samplingRate,
  PpgPeakDetectionConfig? config,
}) => RustLib.instance.api.crateApiPpgProcessPpgFindpeaks(
  signal: signal,
  samplingRate: samplingRate,
  config: config,
);

Future<Uint8List> processPpgFindpeaksMask({
  required List<double> signal,
  required double samplingRate,
}) => RustLib.instance.api.crateApiPpgProcessPpgFindpeaksMask(
  signal: signal,
  samplingRate: samplingRate,
);

class PpgPeakDetectionConfig {
  final double? lowcut;
  final double? highcut;
  final int? filterOrder;
  final double? wPeakSec;
  final double? wBeatSec;
  final double? alpha;
  final double? refractoryPeriodSec;

  const PpgPeakDetectionConfig({
    this.lowcut,
    this.highcut,
    this.filterOrder,
    this.wPeakSec,
    this.wBeatSec,
    this.alpha,
    this.refractoryPeriodSec,
  });

  static Future<PpgPeakDetectionConfig> default_() =>
      RustLib.instance.api.crateApiPpgPpgPeakDetectionConfigDefault();

  @override
  int get hashCode =>
      lowcut.hashCode ^
      highcut.hashCode ^
      filterOrder.hashCode ^
      wPeakSec.hashCode ^
      wBeatSec.hashCode ^
      alpha.hashCode ^
      refractoryPeriodSec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PpgPeakDetectionConfig &&
          runtimeType == other.runtimeType &&
          lowcut == other.lowcut &&
          highcut == other.highcut &&
          filterOrder == other.filterOrder &&
          wPeakSec == other.wPeakSec &&
          wBeatSec == other.wBeatSec &&
          alpha == other.alpha &&
          refractoryPeriodSec == other.refractoryPeriodSec;
}
