// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`

Future<RppgSignalResult> extractRppgFromOpticalSignal({
  required List<double> timestampsSec,
  required List<double> red,
  required List<double> green,
  required List<double> blue,
  required List<int> validPixels,
  RppgConfig? config,
}) => RustLib.instance.api.crateApiRppgExtractRppgFromOpticalSignal(
  timestampsSec: timestampsSec,
  red: red,
  green: green,
  blue: blue,
  validPixels: validPixels,
  config: config,
);

enum RppgAlgorithmId {
  greenChannel,
  chrom,
  pos;

  static Future<RppgAlgorithmId> default_() =>
      RustLib.instance.api.crateApiRppgRppgAlgorithmIdDefault();
}

class RppgConfig {
  final RppgAlgorithmId algorithm;
  final double minQuality;
  final int minimumRoiPixels;
  final double maxGapSec;

  const RppgConfig({
    required this.algorithm,
    required this.minQuality,
    required this.minimumRoiPixels,
    required this.maxGapSec,
  });

  static Future<RppgConfig> default_() =>
      RustLib.instance.api.crateApiRppgRppgConfigDefault();

  @override
  int get hashCode =>
      algorithm.hashCode ^
      minQuality.hashCode ^
      minimumRoiPixels.hashCode ^
      maxGapSec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RppgConfig &&
          runtimeType == other.runtimeType &&
          algorithm == other.algorithm &&
          minQuality == other.minQuality &&
          minimumRoiPixels == other.minimumRoiPixels &&
          maxGapSec == other.maxGapSec;
}

class RppgSignalResult {
  final Float64List timestampsSec;
  final Float64List pulseSignal;
  final double meanQuality;

  const RppgSignalResult({
    required this.timestampsSec,
    required this.pulseSignal,
    required this.meanQuality,
  });

  @override
  int get hashCode =>
      timestampsSec.hashCode ^ pulseSignal.hashCode ^ meanQuality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RppgSignalResult &&
          runtimeType == other.runtimeType &&
          timestampsSec == other.timestampsSec &&
          pulseSignal == other.pulseSignal &&
          meanQuality == other.meanQuality;
}
