// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `from`

Future<Float64List> processRspClean({
  required List<double> signal,
  required double samplingRate,
}) => RustLib.instance.api.crateApiRspProcessRspClean(
  signal: signal,
  samplingRate: samplingRate,
);

Future<List<int>> processRspFindpeaks({
  required List<double> cleanedSignal,
  required double samplingRate,
  RspProcessingConfig? config,
}) => RustLib.instance.api.crateApiRspProcessRspFindpeaks(
  cleanedSignal: cleanedSignal,
  samplingRate: samplingRate,
  config: config,
);

Future<Uint8List> processRspFindpeaksMask({
  required List<double> cleanedSignal,
  required double samplingRate,
  RspProcessingConfig? config,
}) => RustLib.instance.api.crateApiRspProcessRspFindpeaksMask(
  cleanedSignal: cleanedSignal,
  samplingRate: samplingRate,
  config: config,
);

Future<List<RespirationCycle>> processRspCycles({
  required List<double> cleanedSignal,
  required double samplingRate,
  RspProcessingConfig? config,
}) => RustLib.instance.api.crateApiRspProcessRspCycles(
  cleanedSignal: cleanedSignal,
  samplingRate: samplingRate,
  config: config,
);

Future<Float64List> processRspRate({
  required List<double> cleanedSignal,
  required double samplingRate,
  RspProcessingConfig? config,
}) => RustLib.instance.api.crateApiRspProcessRspRate(
  cleanedSignal: cleanedSignal,
  samplingRate: samplingRate,
  config: config,
);

class RespirationCycle {
  final int inspirationIndex;
  final int expirationIndex;
  final int nextInspirationIndex;
  final double durationSec;
  final double respiratoryRateBpm;
  final double amplitude;

  const RespirationCycle({
    required this.inspirationIndex,
    required this.expirationIndex,
    required this.nextInspirationIndex,
    required this.durationSec,
    required this.respiratoryRateBpm,
    required this.amplitude,
  });

  @override
  int get hashCode =>
      inspirationIndex.hashCode ^
      expirationIndex.hashCode ^
      nextInspirationIndex.hashCode ^
      durationSec.hashCode ^
      respiratoryRateBpm.hashCode ^
      amplitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RespirationCycle &&
          runtimeType == other.runtimeType &&
          inspirationIndex == other.inspirationIndex &&
          expirationIndex == other.expirationIndex &&
          nextInspirationIndex == other.nextInspirationIndex &&
          durationSec == other.durationSec &&
          respiratoryRateBpm == other.respiratoryRateBpm &&
          amplitude == other.amplitude;
}

class RspProcessingConfig {
  final double? lowcut;
  final double? highcut;
  final int? filterOrder;
  final double? minBreathIntervalSec;
  final double? maxBreathIntervalSec;
  final double? minAmplitude;

  const RspProcessingConfig({
    this.lowcut,
    this.highcut,
    this.filterOrder,
    this.minBreathIntervalSec,
    this.maxBreathIntervalSec,
    this.minAmplitude,
  });

  static Future<RspProcessingConfig> default_() =>
      RustLib.instance.api.crateApiRspRspProcessingConfigDefault();

  @override
  int get hashCode =>
      lowcut.hashCode ^
      highcut.hashCode ^
      filterOrder.hashCode ^
      minBreathIntervalSec.hashCode ^
      maxBreathIntervalSec.hashCode ^
      minAmplitude.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RspProcessingConfig &&
          runtimeType == other.runtimeType &&
          lowcut == other.lowcut &&
          highcut == other.highcut &&
          filterOrder == other.filterOrder &&
          minBreathIntervalSec == other.minBreathIntervalSec &&
          maxBreathIntervalSec == other.maxBreathIntervalSec &&
          minAmplitude == other.minAmplitude;
}
