// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`, `from`

Future<Float64List> processSignalSmoothMovingAverage({
  required List<double> signal,
  required int windowSize,
}) => RustLib.instance.api.crateApiSignalProcessSignalSmoothMovingAverage(
  signal: signal,
  windowSize: windowSize,
);

Future<Float64List> processSignalFilter({
  required List<double> signal,
  required double samplingRate,
  double? lowcut,
  double? highcut,
  required int order,
}) => RustLib.instance.api.crateApiSignalProcessSignalFilter(
  signal: signal,
  samplingRate: samplingRate,
  lowcut: lowcut,
  highcut: highcut,
  order: order,
);

Future<List<int>> processSignalFindpeaks({required List<double> signal}) =>
    RustLib.instance.api.crateApiSignalProcessSignalFindpeaks(signal: signal);

Future<List<int>> processSignalFindpeaksConfig({
  required List<double> signal,
  required PeakDetectionConfig config,
}) => RustLib.instance.api.crateApiSignalProcessSignalFindpeaksConfig(
  signal: signal,
  config: config,
);

class PeakDetectionConfig {
  final double? minHeight;
  final int? minDistance;
  final double? minProminence;
  final int? minWidth;
  final double? threshold;

  const PeakDetectionConfig({
    this.minHeight,
    this.minDistance,
    this.minProminence,
    this.minWidth,
    this.threshold,
  });

  static Future<PeakDetectionConfig> default_() =>
      RustLib.instance.api.crateApiSignalPeakDetectionConfigDefault();

  @override
  int get hashCode =>
      minHeight.hashCode ^
      minDistance.hashCode ^
      minProminence.hashCode ^
      minWidth.hashCode ^
      threshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeakDetectionConfig &&
          runtimeType == other.runtimeType &&
          minHeight == other.minHeight &&
          minDistance == other.minDistance &&
          minProminence == other.minProminence &&
          minWidth == other.minWidth &&
          threshold == other.threshold;
}
