// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Float64List> processSignalSmoothMovingAverage({
  required List<double> signal,
  required BigInt windowSize,
}) => RustLib.instance.api.crateApiSimpleProcessSignalSmoothMovingAverage(
  signal: signal,
  windowSize: windowSize,
);

Future<Float64List> processSignalFilter({
  required List<double> signal,
  required double samplingRate,
  double? lowcut,
  double? highcut,
  required BigInt order,
}) => RustLib.instance.api.crateApiSimpleProcessSignalFilter(
  signal: signal,
  samplingRate: samplingRate,
  lowcut: lowcut,
  highcut: highcut,
  order: order,
);

Future<List<bool>> processSignalFindpeaks({required List<double> signal}) =>
    RustLib.instance.api.crateApiSimpleProcessSignalFindpeaks(signal: signal);

Future<Float64List> processEcgClean({
  required List<double> signal,
  required double samplingRate,
  required String method,
}) => RustLib.instance.api.crateApiSimpleProcessEcgClean(
  signal: signal,
  samplingRate: samplingRate,
  method: method,
);

Future<List<bool>> processEcgFindpeaks({
  required List<double> signal,
  required double samplingRate,
}) => RustLib.instance.api.crateApiSimpleProcessEcgFindpeaks(
  signal: signal,
  samplingRate: samplingRate,
);

Future<Float64List> processPpgClean({
  required List<double> signal,
  required double samplingRate,
}) => RustLib.instance.api.crateApiSimpleProcessPpgClean(
  signal: signal,
  samplingRate: samplingRate,
);

Future<List<bool>> processPpgFindpeaks({
  required List<double> signal,
  required double samplingRate,
}) => RustLib.instance.api.crateApiSimpleProcessPpgFindpeaks(
  signal: signal,
  samplingRate: samplingRate,
);

Future<Float64List> processEdaClean({
  required List<double> signal,
  required double samplingRate,
}) => RustLib.instance.api.crateApiSimpleProcessEdaClean(
  signal: signal,
  samplingRate: samplingRate,
);

Future<Float64List> processEdaPhasic({
  required List<double> signal,
  required double samplingRate,
}) => RustLib.instance.api.crateApiSimpleProcessEdaPhasic(
  signal: signal,
  samplingRate: samplingRate,
);

Future<List<bool>> processEdaFindpeaks({required List<double> phasicSignal}) =>
    RustLib.instance.api.crateApiSimpleProcessEdaFindpeaks(
      phasicSignal: phasicSignal,
    );

Future<Float64List> processRspClean({
  required List<double> signal,
  required double samplingRate,
}) => RustLib.instance.api.crateApiSimpleProcessRspClean(
  signal: signal,
  samplingRate: samplingRate,
);

Future<List<bool>> processRspFindpeaks({required List<double> cleanedSignal}) =>
    RustLib.instance.api.crateApiSimpleProcessRspFindpeaks(
      cleanedSignal: cleanedSignal,
    );

Future<Float64List> processPeaksToIntervals({
  required List<bool> peaks,
  required double samplingRate,
}) => RustLib.instance.api.crateApiSimpleProcessPeaksToIntervals(
  peaks: peaks,
  samplingRate: samplingRate,
);

Future<double?> processHrvRmssd({required List<double> intervals}) =>
    RustLib.instance.api.crateApiSimpleProcessHrvRmssd(intervals: intervals);

Future<double?> processHrvMeanNn({required List<double> intervals}) =>
    RustLib.instance.api.crateApiSimpleProcessHrvMeanNn(intervals: intervals);

Future<double> processSampleEntropy({
  required List<double> signal,
  required BigInt m,
  required double r,
}) => RustLib.instance.api.crateApiSimpleProcessSampleEntropy(
  signal: signal,
  m: m,
  r: r,
);
